### ISSUE TITLE
Escape symbols for running Test Rerun script on Unix systems

### ISSUE THREAD

**Issue by DmitriyGaliev** [hlaueriksson/ConductOfCode#12]
Problem:

When running the script on Unix systems (I did it in Git Actions using Fedora image), the parameter for retries is set improperly because the \ symbol is interpreted as an escape symbol. This results in the following error:

`The test run parameter argument 'TestRunParameters.Parameter(name=/"Retry/", value=/"2/")' is invalid. Please use the format below. Format: TestRunParameters.Parameter(name=\"<name>\", value=\"<value>\").`

I fixed that by escaping slashes with ` as well:

```shell
$parameters = "-- TestRunParameters.Parameter(name=`\`"Retry`\`", value=`\`"$i`\`")"
``` 

but I don't have an opportunity to test it on Windows.
Please consider checking this if/when you have time. And thanks a lot for the script itself, it's amazing!

**Comment by hlaueriksson** [comment]
Thanks for the feedback! I will update the script when I have time.

You can also check out this dotnet tool; https://github.com/joaoopereira/dotnet-test-rerun

**Comment by DmitriyGaliev** [comment]
It seems I was wrong. No matter how I try to escape that backslash symbol, it is being replaced with forward slash by the terminal, as the parameter part is still interpreted as a command. I will try out the dotnet tool, thank you!

**Comment by DmitriyGaliev** [comment]
I solved it by running the command through the Powershell core. Posting the changed part here in case someone will have a similar issue:

    # Retry
    for ($i = 1; $i -le $retries; $i++) {          

        $startIndex = $fqn.IndexOf('(') + 1
        $filterRegex = $fqn.Substring(0, $startIndex-1)
        
        $filter = "--filter FullyQualifiedName~$filterRegex";
        $fullCommand = @"
        dotnet test . --no-build --logger '`"console;verbosity=detailed`"' --configuration $configuration  $(Get-Option "--settings" $settings) --% $filter -- TestRunParameters.Parameter(name=\`"Retry\`", value=\`"$i\`")
"@

    #Run command through PowerShell 
    $res = Start-Process pwsh -ArgumentList "-Command $fullCommand" -Wait
        

        if ($res) {
            # Passed!
            $passedTests.Add($fqn)
            break
        }
    }

    if (!$res) {
        # Failed!
        $failedTests.Add($fqn)
    }
}

Had to substring the test name from FullyQualifiedName as the SpecFlow parameters from test data table contain brackets and parenthesis, which is incompatible with dotnet test --filter parameter.

Anyway, thank you for sharing your script! Jättebra!
